project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - ModelagemBuck.ipynb

website:
  title: "Controle do Conversor Buck"
  site-url: https://raphateixeira.github.io/ControleBuck/
  repo-url: https://github.com/raphateixeira/ControleBuck

format:
  html:
    theme: [cosmo, TemaRTx.scss]
    lang: pt-BR
    toc: true
